import type {
  ChatMessage,
  LinkedDevice,
  MessageAttachment,
  MessagingContact,
  MessagingConversation,
} from '../types';

export const CURRENT_USER_ID = 'me';

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60 * 1000);
const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000);
const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000);

const imageAttachment = (id: string, label: string, uri: string): MessageAttachment => ({
  id,
  type: 'image',
  label,
  uri,
  mimeType: 'image/jpeg',
  sizeBytes: 1200000,
  sizeLabel: '1.2 MB',
});

const audioAttachment = (id: string, label: string, durationLabel: string): MessageAttachment => ({
  id,
  type: 'audio',
  label,
  durationLabel,
  accentColor: '#00FF6A',
});

const documentAttachment = (id: string, label: string, sizeLabel: string): MessageAttachment => ({
  id,
  type: 'document',
  label,
  sizeLabel,
  accentColor: '#0072FF',
});

export const seedContacts: MessagingContact[] = [
  {
    id: 'contact_1',
    firstName: 'Aline',
    lastName: 'Mbarga',
    name: 'Aline Mbarga',
    phoneNumber: '699 12 45 33',
    countryCode: '+237',
    avatar: 'https://randomuser.me/api/portraits/women/11.jpg',
    avatarColor: '#0072FF',
    isOnAfroza: true,
    isFavorite: true,
    isOnline: true,
    lastSeenLabel: 'En ligne',
    roleLabel: 'Product Design',
    about: 'Toujours dispo pour verrouiller un flow avant la mise en prod.',
    profileStatus: 'Disponible pour designer, shipper et faire relire.',
    campusLabel: 'Douala Campus',
  },
  {
    id: 'contact_2',
    firstName: 'Noah',
    lastName: 'Tchana',
    name: 'Noah Tchana',
    phoneNumber: '677 50 11 90',
    countryCode: '+237',
    avatar: 'https://randomuser.me/api/portraits/men/14.jpg',
    avatarColor: '#00A3FF',
    isOnAfroza: true,
    isFavorite: false,
    isOnline: false,
    lastSeenLabel: 'Vu il y a 18 min',
    roleLabel: 'React Native Club',
    about: 'Build fast, ship faster.',
    profileStatus: 'En sprint mobile cet apres-midi.',
    campusLabel: 'Yaounde Tech Hub',
  },
  {
    id: 'contact_3',
    firstName: 'Fatou',
    lastName: 'Diallo',
    name: 'Fatou Diallo',
    phoneNumber: '650 80 88 14',
    countryCode: '+221',
    avatar: 'https://randomuser.me/api/portraits/women/18.jpg',
    avatarColor: '#00FF6A',
    isOnAfroza: true,
    isFavorite: false,
    isOnline: true,
    lastSeenLabel: 'En ligne',
    roleLabel: 'Community Lead',
    about: 'Je coordonne les hubs, clubs et mentoring.',
    profileStatus: 'La communaute campus bouge fort aujourd hui.',
    campusLabel: 'Dakar Community',
  },
  {
    id: 'contact_4',
    firstName: 'Prince',
    lastName: 'Ewane',
    name: 'Prince Ewane',
    phoneNumber: '693 77 93 05',
    countryCode: '+237',
    avatar: 'https://randomuser.me/api/portraits/men/21.jpg',
    avatarColor: '#0E3E87',
    isOnAfroza: true,
    isFavorite: true,
    isOnline: false,
    lastSeenLabel: 'Vu aujourd hui a 09:12',
    roleLabel: 'Data Science Lab',
    about: 'Python, IA et cafe noir.',
    profileStatus: 'Focus sur les analytics et la qualite des donnees.',
    campusLabel: 'Buea Lab',
  },
  {
    id: 'contact_5',
    firstName: 'Maya',
    lastName: 'Kouassi',
    name: 'Maya Kouassi',
    phoneNumber: '071 45 02 18',
    countryCode: '+225',
    avatar: 'https://randomuser.me/api/portraits/women/26.jpg',
    avatarColor: '#5F6F87',
    isOnAfroza: true,
    isFavorite: false,
    isOnline: false,
    lastSeenLabel: 'Vu hier',
    roleLabel: 'Media Team',
    about: 'Videos, reels et campagnes campus.',
    profileStatus: 'Montage en cours pour la campagne de lancement.',
    campusLabel: 'Abidjan Studio',
  },
  {
    id: 'contact_6',
    firstName: 'Ibrahim',
    lastName: 'Sow',
    name: 'Ibrahim Sow',
    phoneNumber: '621 41 77 00',
    countryCode: '+224',
    avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
    avatarColor: '#172235',
    isOnAfroza: true,
    isFavorite: false,
    isOnline: true,
    lastSeenLabel: 'En ligne',
    roleLabel: 'Ops and Events',
    about: 'Toujours partant pour organiser un meetup.',
    profileStatus: 'Je cale les salles et la logistique.',
    campusLabel: 'Conakry Events',
  },
  {
    id: 'contact_7',
    firstName: 'Lea',
    lastName: 'Nsame',
    name: 'Lea Nsame',
    phoneNumber: '681 23 22 67',
    countryCode: '+237',
    avatar: 'https://randomuser.me/api/portraits/women/31.jpg',
    avatarColor: '#00C557',
    isOnAfroza: true,
    isFavorite: false,
    isOnline: true,
    lastSeenLabel: 'En ligne',
    roleLabel: 'Finance Club',
    about: 'Events, networking et business cases.',
    profileStatus: 'Preparation du prochain networking etudiant.',
    campusLabel: 'Yaounde Business Club',
  },
  {
    id: 'contact_8',
    firstName: 'Samuel',
    lastName: 'Kone',
    name: 'Samuel Kone',
    phoneNumber: '015 66 77 45',
    countryCode: '+223',
    avatarColor: '#36445A',
    isOnAfroza: false,
    isFavorite: false,
    isOnline: false,
    lastSeenLabel: 'Pas encore sur Afroza',
    roleLabel: 'Contact telephone',
    about: 'Invite-le pour demarrer une discussion.',
    profileStatus: 'Invite par QR ou numero.',
    campusLabel: 'Contact externe',
  },
];

export const seedConversations: MessagingConversation[] = [
  {
    id: 'conv_aline',
    title: 'Aline Mbarga',
    kind: 'direct',
    participantIds: ['contact_1'],
    avatar: 'https://randomuser.me/api/portraits/women/11.jpg',
    avatarColor: '#0072FF',
    subtitle: 'Product Design',
    about: 'Coordination design sprint mobile.',
    unreadCount: 3,
    isFavorite: true,
    isPinned: true,
    isArchived: false,
    isMuted: false,
    isBlocked: false,
    isVerified: false,
    presence: 'online',
    lastSeenLabel: 'En ligne',
    updatedAt: minutesAgo(4),
    previewText: 'Je t envoie les specs du composer dans 5 min.',
    notificationPreference: 'all',
    mediaVisibility: 'visible',
    storageLabel: '842 MB',
    encryptionLabel: 'Chiffrement de bout en bout actif',
    disappearingMode: '7d',
    lockEnabled: false,
    privacyLabel: 'Profil partage avec contacts',
    wallpaperKey: 'lagoon',
  },
  {
    id: 'conv_rn_club',
    title: 'React Native Sprint',
    kind: 'group',
    participantIds: ['contact_1', 'contact_2', 'contact_4', 'contact_6'],
    avatarColor: '#00A3FF',
    subtitle: '4 membres',
    about: 'Sprint hebdo de l equipe mobile.',
    memberCount: 4,
    unreadCount: 1,
    isFavorite: false,
    isPinned: false,
    isArchived: false,
    isMuted: false,
    isBlocked: false,
    isVerified: false,
    presence: 'online',
    lastSeenLabel: '4 membres actifs',
    updatedAt: minutesAgo(19),
    previewText: 'Prince: Je pousse la version Expo Go ce soir.',
    description: 'Canal de coordination pour verrouiller l experience messaging mobile.',
    members: [
      { contactId: 'contact_1', role: 'owner', joinedLabel: 'Ajoutee en premier' },
      { contactId: 'contact_2', role: 'admin', joinedLabel: 'Invite il y a 2 semaines' },
      { contactId: 'contact_4', role: 'member', joinedLabel: 'Invite il y a 6 jours' },
      { contactId: 'contact_6', role: 'member', joinedLabel: 'Invite hier' },
    ],
    notificationPreference: 'mentions',
    mediaVisibility: 'visible',
    storageLabel: '1.8 GB',
    encryptionLabel: 'Chiffrement de bout en bout actif',
    disappearingMode: '24h',
    lockEnabled: false,
    privacyLabel: 'Ajout reserve aux admins',
    wallpaperKey: 'lagoon',
  },
  {
    id: 'conv_campus_hub',
    title: 'Afroza Campus Hub',
    kind: 'community',
    participantIds: ['contact_3', 'contact_5', 'contact_6', 'contact_7'],
    avatarColor: '#00FF6A',
    subtitle: 'Communaute campus',
    about: 'Actualites, jobs et collab entre filieres.',
    memberCount: 248,
    unreadCount: 0,
    isFavorite: true,
    isPinned: false,
    isArchived: false,
    isMuted: false,
    isBlocked: false,
    isVerified: true,
    presence: 'online',
    lastSeenLabel: '248 membres',
    updatedAt: hoursAgo(2),
    previewText: 'Fatou: Session mentoring ouverte pour demain.',
    description: 'Hub principal Afroza Campus pour les actus, jobs, clubs et opportunites de collaboration.',
    members: [
      { contactId: 'contact_3', role: 'owner', joinedLabel: 'Fondatrice' },
      { contactId: 'contact_5', role: 'admin', joinedLabel: 'Admin contenu' },
      { contactId: 'contact_6', role: 'admin', joinedLabel: 'Admin operations' },
      { contactId: 'contact_7', role: 'member', joinedLabel: 'Membre actif' },
    ],
    notificationPreference: 'all',
    mediaVisibility: 'visible',
    storageLabel: '4.1 GB',
    encryptionLabel: 'Chiffrement de bout en bout actif',
    disappearingMode: 'off',
    lockEnabled: true,
    privacyLabel: 'Publication reservee aux admins',
    wallpaperKey: 'sunrise',
  },
  {
    id: 'conv_design_channel',
    title: 'Design Updates',
    kind: 'channel',
    participantIds: ['contact_5'],
    avatarColor: '#0E3E87',
    subtitle: 'Canal officiel',
    about: 'Nouveautes produit et UI kit Afroza.',
    memberCount: 920,
    unreadCount: 5,
    isFavorite: false,
    isPinned: false,
    isArchived: false,
    isMuted: true,
    isBlocked: false,
    isVerified: true,
    presence: 'away',
    lastSeenLabel: 'Publication il y a 2 h',
    updatedAt: hoursAgo(2),
    previewText: 'Nouveau pack d illustrations pour le feed.',
    description: 'Canal de diffusion design Afroza pour assets, updates et guidelines.',
    members: [{ contactId: 'contact_5', role: 'owner', joinedLabel: 'Proprietaire du canal' }],
    notificationPreference: 'mentions',
    mediaVisibility: 'visible',
    storageLabel: '2.7 GB',
    encryptionLabel: 'Chiffrement de bout en bout actif',
    disappearingMode: 'off',
    lockEnabled: false,
    privacyLabel: 'Lecture seule pour les abonnes',
    wallpaperKey: 'midnight',
  },
  {
    id: 'conv_prince',
    title: 'Prince Ewane',
    kind: 'direct',
    participantIds: ['contact_4'],
    avatar: 'https://randomuser.me/api/portraits/men/21.jpg',
    avatarColor: '#172235',
    subtitle: 'Data Science Lab',
    about: 'Coordination data and product.',
    unreadCount: 0,
    isFavorite: true,
    isPinned: false,
    isArchived: false,
    isMuted: false,
    isBlocked: false,
    isVerified: false,
    presence: 'offline',
    lastSeenLabel: 'Vu aujourd hui a 09:12',
    updatedAt: hoursAgo(5),
    previewText: 'Le dashboard analytics avance bien.',
    notificationPreference: 'all',
    mediaVisibility: 'hidden',
    storageLabel: '326 MB',
    encryptionLabel: 'Chiffrement de bout en bout actif',
    disappearingMode: 'off',
    lockEnabled: true,
    privacyLabel: 'Derniere activite visible aux contacts',
    wallpaperKey: 'midnight',
  },
  {
    id: 'conv_ibrahim',
    title: 'Ibrahim Sow',
    kind: 'direct',
    participantIds: ['contact_6'],
    avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
    avatarColor: '#172235',
    subtitle: 'Ops and Events',
    about: 'Events and campus operations.',
    unreadCount: 0,
    isFavorite: false,
    isPinned: false,
    isArchived: false,
    isMuted: false,
    isBlocked: false,
    isVerified: false,
    presence: 'online',
    lastSeenLabel: 'En ligne',
    updatedAt: hoursAgo(8),
    previewText: 'Voice note',
    notificationPreference: 'all',
    mediaVisibility: 'visible',
    storageLabel: '614 MB',
    encryptionLabel: 'Chiffrement de bout en bout actif',
    disappearingMode: '24h',
    lockEnabled: false,
    privacyLabel: 'Partage limite aux contacts',
    wallpaperKey: 'sunrise',
  },
];

export const seedConnectedDevices: LinkedDevice[] = [
  {
    id: 'device_1',
    name: 'MacBook Pro de Karel',
    platform: 'macOS',
    browser: 'Chrome 135',
    location: 'Douala, Cameroun',
    lastSeenLabel: 'Actif maintenant',
    isActive: true,
  },
  {
    id: 'device_2',
    name: 'iPad Air',
    platform: 'iPadOS',
    browser: 'Safari',
    location: 'Yaounde, Cameroun',
    lastSeenLabel: 'Vu hier a 19:42',
    isActive: false,
  },
  {
    id: 'device_3',
    name: 'Windows Campus Lab',
    platform: 'Windows 11',
    browser: 'Edge',
    location: 'Buea, Cameroun',
    lastSeenLabel: 'Vu il y a 3 jours',
    isActive: false,
  },
];

export const seedMessagesByConversation: Record<string, ChatMessage[]> = {
  conv_aline: [
    {
      id: 'msg_aline_1',
      conversationId: 'conv_aline',
      senderId: 'contact_1',
      text: 'Tu peux revoir le flow de la nouvelle discussion ?',
      attachments: [],
      createdAt: minutesAgo(17),
      status: 'read',
      isStarred: true,
    },
    {
      id: 'msg_aline_2',
      conversationId: 'conv_aline',
      senderId: CURRENT_USER_ID,
      text: 'Oui. Je veux aussi rendre le chat plus premium que WhatsApp sur la partie composer.',
      attachments: [],
      createdAt: minutesAgo(12),
      status: 'read',
    },
    {
      id: 'msg_aline_3',
      conversationId: 'conv_aline',
      senderId: 'contact_1',
      text: 'Je t envoie les specs du composer dans 5 min.',
      attachments: [],
      createdAt: minutesAgo(4),
      status: 'read',
      isStarred: true,
      reactions: [
        { emoji: '🔥', userIds: [CURRENT_USER_ID] },
        { emoji: '👍', userIds: ['contact_1'] },
      ],
    },
  ],
  conv_rn_club: [
    {
      id: 'msg_group_1',
      conversationId: 'conv_rn_club',
      senderId: 'contact_2',
      text: 'J ai branche les tabs, je prends les perfs ensuite.',
      attachments: [],
      createdAt: hoursAgo(1),
      status: 'read',
    },
    {
      id: 'msg_group_2',
      conversationId: 'conv_rn_club',
      senderId: 'contact_4',
      text: 'Je pousse la version Expo Go ce soir.',
      attachments: [],
      createdAt: minutesAgo(19),
      status: 'delivered',
      isStarred: true,
      reactions: [{ emoji: '🎓', userIds: ['contact_2', CURRENT_USER_ID] }],
    },
  ],
  conv_campus_hub: [
    {
      id: 'msg_community_1',
      conversationId: 'conv_campus_hub',
      senderId: 'contact_3',
      text: 'Session mentoring ouverte pour demain.',
      attachments: [],
      createdAt: hoursAgo(2),
      status: 'read',
    },
    {
      id: 'msg_community_2',
      conversationId: 'conv_campus_hub',
      senderId: CURRENT_USER_ID,
      text: 'Je peux prendre la partie mobile si vous voulez.',
      attachments: [],
      createdAt: hoursAgo(2),
      status: 'read',
      reactions: [{ emoji: '👏', userIds: ['contact_3', 'contact_5'] }],
    },
    {
      id: 'msg_community_3',
      conversationId: 'conv_campus_hub',
      senderId: 'contact_5',
      text: '',
      attachments: [documentAttachment('doc_community', 'Campus-brand-kit.pdf', '2.4 MB')],
      createdAt: hoursAgo(1),
      status: 'read',
      isStarred: true,
    },
  ],
  conv_design_channel: [
    {
      id: 'msg_channel_1',
      conversationId: 'conv_design_channel',
      senderId: 'contact_5',
      text: 'Nouveau pack d illustrations pour le feed.',
      attachments: [
        imageAttachment(
          'img_channel_1',
          'Feed concept',
          'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80'
        ),
      ],
      createdAt: hoursAgo(2),
      status: 'read',
    },
  ],
  conv_prince: [
    {
      id: 'msg_prince_1',
      conversationId: 'conv_prince',
      senderId: 'contact_4',
      text: 'Le dashboard analytics avance bien.',
      attachments: [],
      createdAt: hoursAgo(5),
      status: 'read',
    },
    {
      id: 'msg_prince_2',
      conversationId: 'conv_prince',
      senderId: CURRENT_USER_ID,
      text: 'Top. On valide les KPIs de retention demain.',
      attachments: [],
      createdAt: hoursAgo(4),
      status: 'read',
      isStarred: true,
    },
  ],
  conv_ibrahim: [
    {
      id: 'msg_ibrahim_1',
      conversationId: 'conv_ibrahim',
      senderId: 'contact_6',
      text: '',
      attachments: [audioAttachment('audio_ibrahim_1', 'Voice note campus', '00:18')],
      createdAt: hoursAgo(8),
      status: 'read',
    },
    {
      id: 'msg_ibrahim_2',
      conversationId: 'conv_ibrahim',
      senderId: CURRENT_USER_ID,
      text: 'Je passe au local B apres le cours.',
      attachments: [],
      createdAt: hoursAgo(7),
      status: 'read',
    },
    {
      id: 'msg_ibrahim_3',
      conversationId: 'conv_ibrahim',
      senderId: 'contact_6',
      text: '',
      attachments: [
        imageAttachment(
          'img_ibrahim_1',
          'Plan salle meetup',
          'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=80'
        ),
      ],
      createdAt: daysAgo(1),
      status: 'read',
    },
  ],
};
